apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: ikulyk404/todoapp:3.0.0
        env:
        - name: DB_HOST
          value: mysql-0.mysql.mysql.svc.cluster.local
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: NAME
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10